name: Build Debian Package for Raspberry Pi

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: arm

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache CMake
      uses: actions/cache@v3
      with:
        path: ~/.cache
        key: ${{ runner.os }}-cmake-${{ hashFiles('**/CMakeLists.txt') }}
        restore-keys: |
          ${{ runner.os }}-cmake-

    - name: Set up Raspberry Pi OS image
      run: |
        docker pull --platform linux/arm/v7 balenalib/raspberry-pi2-debian:buster-build
        docker run --platform linux/arm/v7 --name rpi-build -itd --memory=2g balenalib/raspberry-pi2-debian:buster-build


    - name: Test Environment
      run: |
        docker exec rpi-build echo "Hello World!"
        docker exec rpi-build apt-get changelog git
        

    - name: Install dependencies
      run: |
        docker exec rpi-build install_packages ccache cmake qt5-default qttools5-dev qttools5-dev-tools
