name: Build Debian Package for Raspberry Pi

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  release-raspi:
    name: Release (Raspberry Pi ${{ matrix.arch }})
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        arch: [ armhf, arm64 ]

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Update Packages
        shell: bash
        run: sudo apt-get -yq update

      - name: Prepare Sysroot
        id: pi-sysroot
        uses: mariotaku/raspbian-sysroot-action@v1.3
        with:
          release: bookworm
          packages: ${{github.workspace}}/scripts/raspi/sysroot-packages.list
          arch: ${{ matrix.arch }}

      - name: Install Build Tools
        shell: bash
        run: sudo apt-get -y -qq install crossbuild-essential-${{ matrix.arch }} cmake gettext qt5-default
