name: Build Debian Package for Raspberry Pi

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install and run cowsay
      uses: ethanjli/pinspawn-action@v0.1.1
      with:
        image: rpi-os-image.img
        run: |
          apt-get update
          apt-get install -y cowsay
          /usr/games/cowsay 'I am running in a light-weight namespace container!'

    - name: Run as user pi in booted container
      uses: ethanjli/piqemu-action@v0.1.0
      with:
        image: rpi-os-image.img
        machine: rpi-3b+
        user: pi
        run: |
          sudo apt-get update
          sudo apt-get install -y cowsay build-essential cmake qt5-default
          /usr/games/cowsay "I am $USER!"
